"""Add profile column

Revision ID: 38a22f77e8c8
Revises: 
Create Date: 2024-09-20 21:13:25.225051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38a22f77e8c8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_registration_new_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_registration_new_entry', schema=None) as batch_op:
        batch_op.drop_column('profile')

    # ### end Alembic commands ###
